backend:
  name: git-gateway

# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads"
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"

- name: "home" # Used in routes, e.g., /admin/collections/blog
  label: "Home" # Used in the UI
  folder: "_content/home" # The path to the folder where the documents are stored
  create: false # Allow users to create new documents in this collection
  slug: "data" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "subheading", name: "heading", widget: "string"}
